"""
memory.py (MongoDB Vector Search)
==============================================
Semantic memory layer for OrgForge.

Architecture:
  - MongoDB (mongodb-atlas-local or Atlas) stores all documents and vectors.
  - Embeddings generated by whichever provider matches the active quality_preset:
      local_cpu / local_gpu  → OllamaEmbedder  (fully offline)
      cloud                  → OpenAIEmbedder   (text-embedding-3-large)
                               BedrockEmbedder  (Titan Embeddings G1)

Usage:
    from memory import Memory
    mem = Memory()
"""

import os
import json
import hashlib
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Optional, Any

from pymongo import MongoClient
from pymongo.operations import SearchIndexModel

import requests

logger = logging.getLogger("orgforge.memory")

# ─────────────────────────────────────────────
# CONFIG  (all overridable via environment)
# ─────────────────────────────────────────────
MONGO_URI      = os.environ.get("MONGO_URI", "mongodb://localhost:27017/?directConnection=true")
DB_NAME        = os.environ.get("DB_NAME", "orgforge")
OLLAMA_HOST    = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
EMBED_PROVIDER = os.environ.get("EMBED_PROVIDER", "ollama")
EMBED_MODEL    = os.environ.get("EMBED_MODEL",  "mxbai-embed-large")
EMBED_DIMS     = int(os.environ.get("EMBED_DIMS", "1024"))

# ─────────────────────────────────────────────
# SIM EVENT
# ─────────────────────────────────────────────
@dataclass
class SimEvent:
    type: str
    day: int
    date: str
    actors: List[str]
    artifact_ids: Dict[str, str]
    facts: Dict[str, Any]
    summary: str
    tags: List[str] = field(default_factory=list)

    def to_embed_text(self) -> str:
        return (
            f"[{self.type}] Day {self.day} ({self.date}). "
            f"Actors: {', '.join(self.actors)}. "
            f"Artifacts: {json.dumps(self.artifact_ids)}. "
            f"Facts: {json.dumps(self.facts)}. "
            f"Tags: {', '.join(self.tags)}. "
            f"Summary: {self.summary}"
        )

    def to_dict(self) -> Dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: Dict) -> "SimEvent":
        return cls(
            type=d.get("type", ""),
            day=d.get("day", 0),
            date=d.get("date", ""),
            actors=d.get("actors", []),
            artifact_ids=d.get("artifact_ids", {}),
            facts=d.get("facts", {}),
            summary=d.get("summary", ""),
            tags=d.get("tags", [])
        )

# ─────────────────────────────────────────────
# EMBEDDER INTERFACE
# ─────────────────────────────────────────────
class BaseEmbedder(ABC):
    """All embedders must implement embed() and expose dims."""

    def __init__(self, dims: int):
        self.dims = dims

    @abstractmethod
    def embed(self, text: str) -> List[float]:
        """Return a float vector of length self.dims."""
        ...

    def _fallback(self, text: str) -> List[float]:
        """Deterministic hash-based pseudo-embedding used when provider is unreachable."""
        h   = hashlib.sha256(text.encode()).digest()
        vec = [(b / 255.0) - 0.5 for b in h] * (self.dims // 32 + 1)
        return vec[:self.dims]


# ── LOCAL: Ollama ──────────────────────────────
class OllamaEmbedder(BaseEmbedder):
    """Generates embeddings via a local Ollama instance."""

    def __init__(self, model: str = EMBED_MODEL, host: str = OLLAMA_HOST, dims: int = EMBED_DIMS):
        super().__init__(dims)
        self._model = model
        self._host  = host
        self._ok    = self._check_connection()

    def _check_connection(self) -> bool:
        try:
            r = requests.get(f"{self._host}/api/tags", timeout=3)
            return r.status_code == 200
        except Exception:
            logger.warning(f"[memory] ⚠️  Cannot connect to Ollama at {self._host}. Using fallback hashing.")
            return False

    def embed(self, text: str) -> List[float]:
        if not self._ok:
            return self._fallback(text)
        try:
            r = requests.post(
                f"{self._host}/api/embeddings",
                json={"model": self._model, "prompt": text},
                timeout=30,
            )
            return r.json()["embedding"]
        except Exception as e:
            logger.error(f"[memory] Ollama embedding failed: {e}")
            return self._fallback(text)


# ── CLOUD: OpenAI ──────────────────────────────
class OpenAIEmbedder(BaseEmbedder):
    """
    Generates embeddings via OpenAI API (text-embedding-3-large = 3072 dims).
    Requires: OPENAI_API_KEY environment variable.
    """

    def __init__(self, model: str = EMBED_MODEL, dims: int = EMBED_DIMS):
        super().__init__(dims)
        self._model = model
        try:
            from openai import OpenAI
            self._client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
            self._ok = True
            logger.info(f"[memory] OpenAI embedder ready ({model}, {dims} dims)")
        except ImportError:
            logger.error("[memory] ⚠️  openai package not installed. Run: pip install openai")
            self._ok = False
        except Exception as e:
            logger.error(f"[memory] ⚠️  OpenAI init failed: {e}")
            self._ok = False

    def embed(self, text: str) -> List[float]:
        if not self._ok:
            return self._fallback(text)
        try:
            resp = self._client.embeddings.create(
                model=self._model,
                input=text[:8191],          # OpenAI hard token limit
                dimensions=self.dims,       # text-embedding-3-* supports custom dims
            )
            return resp.data[0].embedding
        except Exception as e:
            logger.error(f"[memory] OpenAI embedding failed: {e}")
            return self._fallback(text)


# ── CLOUD: AWS Bedrock ─────────────────────────
class BedrockEmbedder(BaseEmbedder):
    """
    Generates embeddings via AWS Bedrock Titan Embeddings G1 (1536 dims).
    Requires: boto3, AWS credentials (IAM role, env vars, or ~/.aws/credentials).
    """

    TITAN_MODEL = "amazon.titan-embed-text-v1"
    TITAN_DIMS  = 1536

    def __init__(self, region: str = "us-east-1", dims: int = TITAN_DIMS):
        super().__init__(dims)
        self._region = region
        try:
            import boto3, json as _json
            self._client = boto3.client("bedrock-runtime", region_name=region)
            self._json   = _json
            self._ok     = True
            logger.info(f"[memory] Bedrock embedder ready (Titan G1, {dims} dims, region={region})")
        except ImportError:
            logger.error("[memory] ⚠️  boto3 not installed. Run: pip install boto3")
            self._ok = False
        except Exception as e:
            logger.error(f"[memory] ⚠️  Bedrock init failed: {e}")
            self._ok = False

    def embed(self, text: str) -> List[float]:
        if not self._ok:
            return self._fallback(text)
        try:
            body = self._json.dumps({"inputText": text[:8000]})
            resp = self._client.invoke_model(
                modelId=self.TITAN_MODEL,
                body=body,
                contentType="application/json",
                accept="application/json",
            )
            result = self._json.loads(resp["body"].read())
            return result["embedding"]
        except Exception as e:
            logger.error(f"[memory] Bedrock embedding failed: {e}")
            return self._fallback(text)


# ─────────────────────────────────────────────
# EMBEDDER FACTORY
# ─────────────────────────────────────────────
def build_embedder(
    provider: str = EMBED_PROVIDER,
    model:    str = EMBED_MODEL,
    dims:     int = EMBED_DIMS,
    **kwargs,
) -> BaseEmbedder:
    """
    Return the correct embedder for the active quality_preset.

    provider values:
      "ollama"  → OllamaEmbedder  (local_cpu / local_gpu presets)
      "openai"  → OpenAIEmbedder  (cloud preset, OPENAI_API_KEY required)
      "bedrock" → BedrockEmbedder (cloud preset, AWS credentials required)
    """
    provider = provider.lower()
    if provider == "openai":
        return OpenAIEmbedder(model=model, dims=dims)
    if provider == "bedrock":
        region = kwargs.get("aws_region", os.environ.get("AWS_DEFAULT_REGION", "us-east-1"))
        return BedrockEmbedder(region=region, dims=dims)
    # Default: Ollama (local)
    return OllamaEmbedder(model=model, dims=dims)


# ─────────────────────────────────────────────
# MEMORY (MongoDB)
# ─────────────────────────────────────────────
class Memory:
    def __init__(self, mongo_uri: str = MONGO_URI):
        self._embedder = build_embedder()
        self._client = MongoClient(mongo_uri)
        self._db = self._client[DB_NAME]
        
        self._artifacts = self._db["artifacts"]
        self._events = self._db["events"]
        
        # In-memory ordered log for strict sequential access
        self._event_log: List[SimEvent] = []
        
        self._init_vector_indexes()

    def _init_vector_indexes(self):
        """Creates the Atlas Vector Search indexes if they don't exist."""
        index_definition = {
            "fields": [
                {
                    "type": "vector",
                    "path": "embedding",
                    "numDimensions": EMBED_DIMS,
                    "similarity": "cosine"
                },
                {
                    "type": "filter",
                    "path": "type"
                },
                {
                    "type": "filter",
                    "path": "day"
                }
            ]
        }

        for coll_name in ["artifacts", "events"]:
            # 1. Force creation of the collection if it doesn't exist
            if coll_name not in self._db.list_collection_names():
                try:
                    self._db.create_collection(coll_name)
                    logger.info(f"[memory] Created collection: {coll_name}")
                except Exception as e:
                    # Handle race conditions if another process created it simultaneously
                    pass
            
            coll = self._db[coll_name]
            
            # 2. Proceed with index creation
            existing_indexes = list(coll.list_search_indexes())
            if not any(idx.get("name") == "vector_index" for idx in existing_indexes):
                try:
                    search_index_model = SearchIndexModel(
                        definition=index_definition,
                        name="vector_index",
                        type="vectorSearch"
                    )
                    coll.create_search_index(model=search_index_model)
                    logger.info(f"[memory] Created vector_index on {coll.name}")
                except Exception as e:
                    logger.error(f"[memory] Could not create index on {coll.name}: {e}")

    # ─── WRITE ────────────────────────────────

    def embed_artifact(self, id: str, type: str, title: str, content: str, day: int, date: str, metadata: Optional[Dict] = None):
        """Upsert artifact into MongoDB with vector embedding."""
        embed_text = f"{title}\n\n{content[:2000]}"
        vector = self._embedder.embed(embed_text)

        doc = {
            "_id": id,
            "type": type,
            "title": title,
            "content": content,
            "day": day,
            "date": date,
            "embedding": vector,
            "metadata": metadata or {}
        }
        
        self._artifacts.update_one({"_id": id}, {"$set": doc}, upsert=True)

    def log_event(self, event: SimEvent):
        """Insert SimEvent into MongoDB."""
        self._event_log.append(event)
        event_id = f"EVT-{event.day}-{event.type}-{len(self._event_log)}"
        
        vector = self._embedder.embed(event.to_embed_text())
        
        doc = event.to_dict()
        doc["_id"] = event_id
        doc["embedding"] = vector
        
        self._events.update_one({"_id": event_id}, {"$set": doc}, upsert=True)

    # ─── READ ─────────────────────────────────

    def recall(self, query: str, n: int = 5, type_filter: Optional[str] = None, day_range: Optional[tuple] = None) -> List[Dict]:
        """Hybrid vector + metadata search over artifacts."""
        query_vec = self._embedder.embed(query)
        
        # Build the exact-match pre-filter for MongoDB Vector Search
        filter_doc = {}
        if type_filter:
            filter_doc["type"] = {"$eq": type_filter}
        if day_range:
            filter_doc["day"] = {"$gte": day_range[0], "$lte": day_range[1]}

        pipeline = [
            {
                "$vectorSearch": {
                    "index": "vector_index",
                    "path": "embedding",
                    "queryVector": query_vec,
                    "numCandidates": max(n * 10, 100), # MongoDB requirement for optimal ANN search
                    "limit": n,
                }
            }
        ]
        
        # Add filter if it exists
        if filter_doc:
            pipeline[0]["$vectorSearch"]["filter"] = filter_doc

        # Project output to calculate score and remove raw vector array
        pipeline.append({
            "$project": {
                "id": "$_id",
                "title": 1,
                "type": 1,
                "day": 1,
                "date": 1,
                "score": {"$meta": "vectorSearchScore"}
            }
        })

        try:
            results = list(self._artifacts.aggregate(pipeline))
            return results
        except Exception as e:
            logger.error(f"[memory] recall failed: {e}")
            return []

    def recall_events(
        self,
        query: str,
        n: int = 3,
        as_of_day: Optional[int] = None,
    ) -> List[SimEvent]:
        """
        Returns the n most relevant SimEvents for the query.
        If as_of_day is provided, restricts to events on or before that day.
        """
        query_filter = {}
        if as_of_day is not None:
            query_filter["day"] = {"$lte": as_of_day}

        # Assuming recall_events currently does a text/vector search —
        # add the day filter to whatever query it's already building.
        # If it's a simple find(), it becomes:
        results = (
            self._events
            .find(query_filter)
            .sort("day", -1)
            .limit(n * 3)
        )

        # Re-rank by relevance to query if you have embeddings on events,
        # otherwise just return the most recent n within the day window
        events = [SimEvent(**e) for e in results]
        return events[:n]

    # ─── HELPERS ──────────────────────────────

    def persona_history(self, name: str, n: int = 4) -> List[SimEvent]:
        relevant = [e for e in self._event_log if name in e.actors]
        return relevant[-n:]

    def get_event_log(self) -> List[SimEvent]:
        return list(self._event_log)

    def events_by_type(self, event_type: str) -> List[SimEvent]:
        return [e for e in self._event_log if e.type == event_type]

    def context_for_prompt(
        self,
        query: str,
        n: int = 4,
        as_of_day: Optional[int] = None,
    ) -> str:
        """
        Semantic search over embedded artifacts and events.
        If as_of_day is provided, restricts results to artifacts created
        on or before that day — simulating what was knowable at that point.
        """
        lines = []

        # ── Artifact search (temporal filter applied here) ────────────────
        artifact_count = self._artifacts.estimated_document_count()
        oversample     = max(n * 3, min(artifact_count // 10, 200))

        pipeline = [
            {
                "$vectorSearch": {
                    "queryVector":  self._embedder.embed(query),
                    "path":         "embedding",
                    "numCandidates": oversample,
                    "limit":        n if as_of_day is None else oversample,
                    "index":        "vector_index",
                }
            }
        ]

        if as_of_day is not None:
            pipeline.append({"$match": {"day": {"$lte": as_of_day}}})
            pipeline.append({"$limit": n})

        pipeline.append({
            "$project": {
                "content": 1,
                "title":   1,
                "day":     1,
                "type":    1,
                "id":      1,
                "score":   {"$meta": "vectorSearchScore"},
            }
        })

        artifacts = list(self._artifacts.aggregate(pipeline))

        if artifacts:
            lines.append("=== RELEVANT ARTIFACTS ===")
            for a in artifacts:
                day_label = f"Day {a.get('day')}" if "day" in a else "?"
                lines.append(
                    f"  [{a.get('type', '').upper()}] {a.get('id')} — "
                    f"{a.get('title')} ({day_label}, "
                    f"relevance {a.get('score', 0):.3f})"
                )

        # ── Event search (temporal filter applied here too) ───────────────
        events = self.recall_events(query, n=3, as_of_day=as_of_day)

        if events:
            lines.append("=== RELEVANT EVENTS ===")
            for e in events:
                lines.append(
                    f"  Day {e.day} ({e.date}) [{e.type}]: {e.summary} "
                    f"| actors={e.actors} | artifacts={e.artifact_ids} "
                    f"| facts={e.facts}"
                )

        if not lines:
            return "No relevant prior context found."

        return "\n".join(lines)

    def facts_for_event_type(self, event_type: str) -> List[Dict]:
        return [e.facts | {"date": e.date, "actors": e.actors, "artifact_ids": e.artifact_ids}
                for e in self.events_by_type(event_type)]

    def stats(self) -> Dict:
        embedder_ok = getattr(self._embedder, "_ok", True)
        return {
            "artifact_count":   self._artifacts.count_documents({}),
            "event_count":      self._events.count_documents({}),
            "event_log_len":    len(self._event_log),
            "embed_provider":   EMBED_PROVIDER,
            "embed_model":      EMBED_MODEL,
            "embed_dims":       self._embedder.dims,
            "embedder_ok":      embedder_ok,
            "mongodb_ok":       True,
        }